---
title: "Literature Synthesis"
author: "Group 10 members"
date: "4/12/2017"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr);
library("stringr");
library(ggplot2);
library(dplyr);
library(tidyr);
library(RColorBrewer);
library(dendextend);
library(gplots);
library(cluster);
library(igraph)
library(ggraph)
library(gridExtra)
library(grid)
library(gProfileR) ## might need to be installed
library(org.Sc.sgd.db)

```

```{r}
columns(org.Sc.sgd.db)
select(org.Sc.sgd.db, "YAL022C", "ALIAS")
```


```{r}
kuang <- read.csv("./datasets/kuang-2014-microarray-expression.csv") ##local- needs to be changed 
kuang_t <- as.data.frame(t(kuang[,-1]))
n <- kuang$Gene.name # first remember the names
colnames(kuang_t) <- n
kuang_t.cor <- kuang_t %>% cor(use="pairwise.complete.obs")  ##generate correlation measurements
kuang.dist <- as.dist(1 - kuang_t.cor)  ##use correlation to find distance measurements 
kuang.tree <- hclust(kuang.dist, method="complete")
kuang.dend <- as.dendrogram(kuang.tree) ## created & priviewed dendrogram object
k=3
kuang.kmedoids <- pam(kuang.dist, k) # create k-medoids clustering with k clusters
kclusters <- kuang.kmedoids$cluster
kclusters <- kclusters[order.dendrogram(kuang.dend)]
```

```{r}
kcluster1.genes <- names(kclusters[kclusters == 1])
kcluster2.genes <- names(kclusters[kclusters == 2])
kcluster3.genes <- names(kclusters[kclusters == 3])
```

#GO for K-means cluster 1
```{r}

cluster1.profile <- gprofiler(kcluster1.genes, 
                       organism = "scerevisiae",
                       max_p_value = 0.05,  # set p-value cutoff
                       src_filter = "GO", # only consider GO biological process
                       hier_filtering = "moderate"
                       )
cluster1.profile.sorted <- cluster1.profile[order(cluster1.profile$p.value),] 
cluster1.profile.sorted
##cat(as.character(kcluster1.first100), quote=F,sep="\n")
```
**catabolic process:**
GENETICS March 1, 2012 vol. 190 no. 3 885-929; https://doi.org/10.1534/genetics.111.133306


#GO for K-means cluster 2
```{r}
cluster2.profile <- gprofiler(kcluster2.genes, 
                       organism = "scerevisiae",
                       max_p_value = 0.05,  # set p-value cutoff
                       src_filter = "GO", # only consider GO biological process
                       hier_filtering = "moderate"
                       )
cluster2.profile.sorted <- cluster2.profile[order(cluster2.profile$p.value),] 
cluster2.profile.sorted
##cat(as.character(kcluster2.first100), quote=F,sep="\n")

```

*Note: chromatin assembly or disassembly** 

#GO for K-means cluster 3
```{r}

#just get first 100
kcluster3.first100 <- kcluster3.genes[1:100]

##cat(as.character(kcluster3.first100), quote=F,sep="\n")
cluster3.profile <- gprofiler(kcluster3.genes, 
                       organism = "scerevisiae",
                       max_p_value = 0.05,  # set p-value cutoff
                       src_filter = "GO", # only consider GO biological process
                       hier_filtering = "moderate"
                       )
cluster3.profile.sorted <- cluster3.profile[order(cluster3.profile$p.value),] 
cluster3.profile.sorted
```


#TF Binding Clusters
```{r}

kuangtf <- read.csv("./datasets/kuang-2014-TFbinding.csv")
time <- read.csv("./datasets/kuang-2014-TFbinding-timepts.csv")
kuangrna <- read.csv("./datasets/kuang-2014-rnaseq-expression.csv")   ##used later - included in the import section of the code for clarity

Gcn <- kuangtf[,c(1:15)]
Esa <- kuangtf[,c(1,16:29)]
Set <- kuangtf[,c(1,30:43)]

Gcn.data <- as.data.frame(t(Gcn[,-1]))
colnames(Gcn.data) <- Gcn$Gene.ID
Gcn.time <- cbind(Gcn.data, time = time$hour)

Esa.data <- as.data.frame(t(Esa[,-1]))
colnames(Esa.data) <- Esa$Gene.ID
Esa.time <- cbind(Esa.data, time = time$hour)

Set.data <- as.data.frame(t(Set[,-1]))
colnames(Set.data) <- Set$Gene.ID
Set.time <- cbind(Set.data, time = time$hour)

#get the genes in the tf and rna data
TF.genes <- unique(kuangtf[,1])
rna.genes <- unique(kuangrna[,1])

#get rid of duplicated rows in the rna data
rna.unique <- unique(kuangrna)

#filter the rna data for the tf genes
rna.Genes <- filter(rna.unique, rna.unique[,1] %in% TF.genes)

#get the unique genes from this rna data
#may not need to do this again but did it just to be safe
rna.genes.u <- unique(rna.Genes[,1])

#It appears that all of the genes present in the TF data are not present in the rna data
#So need to filter again to get rid of these genes
kuangtf.new <- filter(kuangtf, TF.genes %in% rna.genes.u)

#now remove last two columns so the times add up
rna.new <- rna.Genes[,1:15]

dim(rna.new)
dim(kuangtf.new)

#now extract the different TFs
Gcn.new <- kuangtf.new[,c(1:15)]
dim(Gcn.new)
Esa.new <- kuangtf.new[,c(1,16:29)]
dim(Esa.new)
Set.new <- kuangtf.new[,c(1,30:43)]
dim(Set.new)

#here we see the 69 genes that are in the TF data but not the rnaseq
length(which( ! TF.genes %in% rna.genes))

#sort so that the genes are in the same order
Gcn.sorted <- Gcn.new[match(rna.new[,1], Gcn.new[,1]),]
Esa.sorted <- Esa.new[match(rna.new[,1], Esa.new[,1]),]
Set.sorted <- Set.new[match(rna.new[,1], Set.new[,1]),]
#preview
head(Gcn.sorted[,1:5])
head(Esa.sorted[,1:5])
head(Set.sorted[,1:5])
head(rna.new[,1:5])

```

```{r}
##Need to drop gene name
Gcn.sorted.cor <- dplyr::select(Gcn.sorted, -Gene.ID)
Esa.sorted.cor <- dplyr::select(Esa.sorted, -Gene.ID)
Set.sorted.cor <- dplyr::select(Set.sorted, -Gene.ID)
rna.new.cor <- dplyr::select(rna.new, -Gene.name)
corValues.Gcn <- sapply(1:nrow(Gcn.sorted.cor), function(i) cor(as.numeric(Gcn.sorted.cor[i,]), as.numeric(rna.new.cor[i,])))
corValues.Esa <- sapply(1:nrow(Esa.sorted.cor), function(i) cor(as.numeric(Esa.sorted.cor[i,]), as.numeric(rna.new.cor[i,])))
corValues.Set <- sapply(1:nrow(Set.sorted.cor), function(i) cor(as.numeric(Set.sorted.cor[i,]), as.numeric(rna.new.cor[i,])))
df.cors <- data.frame(corValues.Gcn, corValues.Esa, corValues.Set) 
head(df.cors)
```
```{r}
# But first lets append the gene names to the df.cors dataframe for more informative display
df.cors.w.names <- df.cors
row.names(df.cors.w.names) <- Gcn.sorted$Gene.ID #doesn't matter what set the names comes from - they are all the same 
head(df.cors.w.names)
```
```{r}
Gcn.indexes <- which(df.cors.w.names[,1] > .75)
Gcn.genes.above <- kuangtf.new[Gcn.indexes, 1]
Esa.indexes <- which(df.cors[,2] > .75)
Esa.genes.above <- kuangtf.new[Esa.indexes, 1]
Set.indexes <- which(df.cors[,3] > .75)
Set.genes.above <- kuangtf.new[Set.indexes, 1]
#print first 10 genes for each TF that meet threshold
head(df.cors.w.names[Gcn.indexes,1, drop = FALSE], 10) 
head(df.cors.w.names[Esa.indexes,2, drop = FALSE], 10) 
head(df.cors.w.names[Set.indexes,3, drop = FALSE], 10) 
```

```{r}
df.cors["gene"] = Set.sorted["Gene.ID"]
df.cors.single <- df.cors %>% 
  tidyr::gather(TF, corr, -gene) %>% # cast to long format
  dplyr::select(TF, gene, corr)
df.cors.single.trimmed <- filter(df.cors.single, corr > 0.75)

gcn <- filter(df.cors.single.trimmed, TF=="corValues.Gcn")
esa <- filter(df.cors.single.trimmed, TF=="corValues.Esa")
set <- filter(df.cors.single.trimmed, TF=="corValues.Set")
```
```{r}
# Biological Process
gcn.bp <- gprofiler(gcn, 
                          organism = "scerevisiae",
                          max_p_value = 0.05,  # set p-value cutoff
                          src_filter = "GO:BP", # only consider GO biological process
                          hier_filtering = "moderate")
gcn.bp

esa.bp <- gprofiler(esa, 
                          organism = "scerevisiae",
                          max_p_value = 0.05,  # set p-value cutoff
                          src_filter = "GO:BP", # only consider GO biological process
                          hier_filtering = "moderate")
esa.bp

set.bp <- gprofiler(set, 
                          organism = "scerevisiae",
                          max_p_value = 0.05,  # set p-value cutoff
                          src_filter = "GO:BP", # only consider GO biological process
                          hier_filtering = "moderate")
set.bp
```

```{r}
# Molecular Function
gcn.mf <- gprofiler(gcn, 
                          organism = "scerevisiae",
                          max_p_value = 0.05,  # set p-value cutoff
                          src_filter = "GO:MF", # only consider GO molecular function
                          hier_filtering = "moderate")
gcn.mf

esa.mf <- gprofiler(esa, 
                          organism = "scerevisiae",
                          max_p_value = 0.05,  # set p-value cutoff
                          src_filter = "GO:MF", # only consider GO molecular function
                          hier_filtering = "moderate")
esa.mf

set.mf <- gprofiler(set, 
                          organism = "scerevisiae",
                          max_p_value = 0.05,  # set p-value cutoff
                          src_filter = "GO:MF", # only consider GO molecular function
                          hier_filtering = "moderate")
set.mf
```
```{r}
# Cellular Component
gcn.cc <- gprofiler(gcn, 
                          organism = "scerevisiae",
                          max_p_value = 0.05,  # set p-value cutoff
                          src_filter = "GO:CC", # only consider GO cellular component
                          hier_filtering = "moderate")
gcn.cc

esa.cc <- gprofiler(esa, 
                          organism = "scerevisiae",
                          max_p_value = 0.05,  # set p-value cutoff
                          src_filter = "GO:CC", # only consider GO cellular component
                          hier_filtering = "moderate")
esa.cc

set.cc <- gprofiler(set, 
                          organism = "scerevisiae",
                          max_p_value = 0.05,  # set p-value cutoff
                          src_filter = "GO:CC", # only consider GO cellular component
                          hier_filtering = "moderate")
set.cc
```

#RnaSeq
```{r}

rnaseq <- read.csv("./datasets/kuang-2014-rnaseq-expression.csv") #local needs to be changed
rnatime <- read.csv("./datasets/kuang-2014-rnaseq-expression-timepts.csv")
# first remember the names
nrna <- rnaseq$Gene.name

# transpose all but the first column (Gene.name)
rnaseq_t_zeros <- as.data.frame(t(rnaseq[,-1]))
colnames(rnaseq_t_zeros) <- nrna

rnaseq_t_zeros.time <- cbind(rnaseq_t_zeros, time = rnatime$hour)

rnaseq_t <- rnaseq_t_zeros[, colSums(rnaseq_t_zeros != 0) > 0]
rnaseq_t.time <- cbind(rnaseq_t, time = rnatime$hour)

rnaseq.cor <- cor(rnaseq_t, use = "pairwise.complete.obs") 
rnaseq.dist <- as.dist(1-rnaseq.cor)

rnaseq.tree <- hclust(rnaseq.dist, method = "complete") 
rnaseq.dend <- as.dendrogram(rnaseq.tree)

rnaseq.clusters <- cut(rnaseq.dend, h = 1.9)

rnaseq.clusters.cluster1 <- cut(rnaseq.clusters$lower[[1]], h = 1.5)
rnaseq.clusters.cluster1.clusterAgain <- cut(rnaseq.clusters.cluster1$lower[[1]], h = 1.2)

rnaseq.clusters.cluster2 <- cut(rnaseq.clusters$lower[[2]], h = 1.6)

rnaseq.clusters.cluster3 <- cut(rnaseq.clusters$lower[[3]], h = 1.3)
rnaseq.clusters.cluster3.cutAgain <- cut(rnaseq.clusters.cluster3$lower[[1]], h = .85)

rnaseq.clusters.cluster4 <- cut(rnaseq.clusters$lower[[4]], h = 1.48)
```

